import Head from "next/head";
import Landing from "../components/landing";
import Game from "../components/game";

export default function Home(props) {
  return (
    <div className="container">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {props.authUser ? (
        <Game user={props.user} userLoading={props.userLoading} />
      ) : (
        <Landing />
      )}
    </div>
  );
}
